name: Deploy back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy back
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./apps/back
          file: ./apps/back/Dockerfile
          push: true
          tags: fufu2345/aidev-back:latest

      - name: Deploy to Server and Create .env
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/myproject 
            
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_SERVER=db" >> .env
            echo "POSTGRES_PORT=5432" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> .env
            echo "ollamaURL=${{ secrets.OLLAMA_URL }}" >> .env
            echo "stabilityModel=${{ secrets.STABILITY_MODEL }}" >> .env
            echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> .env
            echo "SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }}" >> .env
            echo "F5_API_URL=http://sound:8001/internal/generate" >> .env
            
            docker compose pull
            docker compose up -d